const StringConst = {
    appName: "Laundry App",
    applianceHeading: 'Please select the equipment that contains the laundry',
    equipmentOne: 'Washing and drying',
    equipmentTwo: 'Laundry',
    equipmentThree: 'Drying',
    equipmentFour: 'Sneaker washing and drying',
    availablePayment: 'Available payment methods',
    courseDesired: 'Please select your desired course',
    machineSelection:
      'Please select the machine number where the laundry is placed.',
    courseOne: 'Plenty of washing and drying (15kg)',
    courseTwo: 'Light wash and dry (11kg)',
    courseThree: 'Washing only (15kg)',
    courseFour: 'Dry only (11kg)',
    paypay: 'PayPay',
    aupay: 'auPAY',
    dPayment: 'dPayment',
    rpay: 'R Pay',
    paymentNote:
      '* Once payment is completed, the device will start operating.',
    scanWithDevice:
      'Scan the QR code with your device to complete the payment.',
    makePayment: 'Please make payment',
    choosePayment: 'Choose your payment method',
    thankyouService: 'Thank you for using our service.',
    completion: 'completion',
    completionNote: '*Return to top in',
    seconds: 'seconds',
    return: 'Return',
    cancel: 'Cancel',
    min:'min',
    timeRangeHeading:'Please select the usage time range',
    usingTimeHeading:'Please select your usage time',
    footerText: 'LaundryPay Smart',
    paymentExpired:' Payment Expired. Please try again.',
    paymentError:' Error loading QR code',
    paymentRetry:' Retry Payment',
    yen:'yen',
    kg:'kg',
    to:' to ',
    minutes:'minutes'
};

export default StringConst
