const StringConstJap = {
  appName: "ランドリーアプリ",
  applianceHeading: "洗濯物を入れる機器を選択してください",
  equipmentOne: "洗濯乾燥",
  equipmentTwo: "洗濯",
  equipmentThree: "乾燥",
  equipmentFour: "スニーカー洗濯乾燥",
  availablePayment: "利用可能な支払い方法",
  courseDesired: "希望のコースを選択してください",
  machineSelection: "洗濯物を入れた機械番号を選択してください",
  courseOne: "たっぷり洗濯乾燥（15kg）",
  courseTwo: "軽量洗濯乾燥（11kg）",
  courseThree: "洗濯のみ（15kg）",
  courseFour: "乾燥のみ（11kg）",
  paypay: "PayPay",
  aupay: "auPAY",
  dPayment: "dPayment",
  rpay: "R Pay",
  paymentNote: "* 支払い完了後、機器が作動します。",
  scanWithDevice: "デバイスでQRコードをスキャンして支払いを完了してください。",
  makePayment: "お支払いください",
  choosePayment: "支払い方法を選択してください",
  thankyouService: "ご利用いただきありがとうございます",
  completion: "完了",
  completionNote: "* 上部に戻るまで",
  seconds: "秒",
  return: "戻る",
  cancel: "キャンセル",
  min: "分",
  timeRangeHeading: "使用時間範囲を選択してください",
  usingTimeHeading: "使用時間を選択してください",
  footerText: "LaundryPay Smart",
  paymentExpired: "支払い期限切れです。もう一度お試しください。",
  paymentError: "QRコードの読み込みエラー",
  paymentRetry: "再試行",
  yen: "円",
  kg: "kg",
  to: " ～ ",
  minutes: "分",
  deviceOperate: "機器を起動する",
};

export default StringConstJap;
